font: Carlito
margins: compact
spacing: compact
h1:
  font_size: 20
  center: True
  line: False
h2:
  font_size: 14
  center: False
  line: True
body:
  font_size: 11
bullet:
  char: '-' # TODO: use "•" with unicode font
  indent: compact
  space_after: True
line:
  width: standard
